Update ruler rules on API based update
cortexproject/cortex pull request #3208
Opened 2020-09-18 16:01 UTC by gouthamve

Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

**What this PR does**:

Today, there is a 1min delay until the sees the update they made via the experimental API. In this PR, I am forcing a best effort config reload whenever a user updates their config.

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2020-09-18 19:36 UTC, jtlisi commented on pkg/ruler/ruler.go
> +	r.loadRules(ctx, userID)
```suggestion
	go r.loadRules(ctx, userID)
```

Might as well run this in the background since no error is returned at this point.

2020-09-18 19:36 UTC, jtlisi commented on pkg/ruler/ruler.go
> +	wg.Wait()
**question**: Since this is best effort should we both waiting for every ruler to respond?

2020-09-21 09:02 UTC, pracucci reviewed
When running multiple rulers, this best-effort approach works only for the ruler where the API was executed, correct?

2020-09-21 10:24 UTC, pracucci commented
> When running multiple rulers, this best-effort approach works only for the ruler where the API was executed, correct?

Ignore it. It was too quick. Your idea is good 👍

2020-09-28 10:42 UTC, pstibrany requested changes

2020-09-28 10:42 UTC, pstibrany commented on pkg/ruler/ruler.go
> +
This is dangerous. `r.manager.SyncRuleGroups` always needs *All* users to be present in the map, with all of the rules. If it doesn't find the user in the supplied map, rules manager for given user is stopped and removed from memory.

2020-10-02 10:18 UTC, gouthamve commented
Superceded by #3268

2020-10-02 10:18 UTC, closed without merging