Use path.Join to concatenate prefix and folder string (#2643)
cortexproject/cortex pull request #3981
Opened 2021-03-19 21:48 UTC by ChinYing-Li

Signed-off-by: ChinYing-Li <chinying.li@mail.utoronto.ca>

**What this PR does**:
Properly concatenates url

**Which issue(s) this PR fixes**:
Fixes #2643.
I am not sure whether this counts as a BUGFIX or a ENHANCEMENT.
Any suggestion is appreciated!

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-03-21 16:23 UTC, jtlisi requested changes
One nit, otherwise this seems reasonable to me.

2021-03-21 16:23 UTC, jtlisi commented on pkg/api/api.go
> +	f.StringVar(&cfg.PrometheusHTTPPrefix, path.Join(prefix, "http.prometheus-http-prefix"), "/prometheus", "HTTP URL path under which the Prometheus api will be served.")
**nit:** These are flags, no URL routes. The prefix is meant to be concatenated as it currently is.

2021-03-22 16:09 UTC, pstibrany commented
Should we fix `NewQuerierHandler` in handlers.go too? (at the end, where `cfg.PrometheusHTTPPrefix` and `cfg.LegacyHTTPPrefix` are used)

2021-03-22 17:18 UTC, pracucci commented
> Should we fix `NewQuerierHandler` in handlers.go too? (at the end, where `cfg.PrometheusHTTPPrefix` and `cfg.LegacyHTTPPrefix` are used)

I think so. @ChinYing-Li do you mind taking a look, please?

2021-03-23 08:57 UTC, pracucci reviewed
Good job! I left a comment about a typo which slipped in and then LGTM.

2021-03-23 08:57 UTC, pracucci commented on pkg/api/api.go
> +	a.RegisterRoute(path.Join(a.cfg.LegacyHTTPPrefix, "/rules/{namespace}/{groupName})"), http.HandlerFunc(r.GetRuleGroup), true, "GET")
A `)` slipped in.

```suggestion
	a.RegisterRoute(path.Join(a.cfg.LegacyHTTPPrefix, "/rules/{namespace}/{groupName}"), http.HandlerFunc(r.GetRuleGroup), true, "GET")
```

2021-03-23 14:07 UTC, pracucci approved these changes
LGTM, thanks!

2021-03-23 14:41 UTC, jtlisi approved these changes
LGTM

2021-03-23 15:10 UTC, pstibrany commented
Thanks!

2021-03-23 15:10 UTC, merged