Downstream url documentation
cortexproject/cortex pull request #4570
Opened 2021-11-25 19:39 UTC by srijan55

**What this PR does**:
Adds some documentation about downstream_url config in Frontend.
**Which issue(s) this PR fixes**:
Fixes #3039

**Checklist**
- [ ] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2021-11-25 20:47 UTC, andsens requested changes
Awesome. This explains very succinctly what the parameter is for.

2021-11-25 20:47 UTC, andsens commented on docs/architecture.md
> +Query frontend can also be used with any Prometheus-API compatible service. In this mode Cortex can be used as an query accelerator with it's caching and splitting features on other prometheus query
> which is endpoint of the prometheus server

"which is *the* endpoint...

2021-11-25 20:47 UTC, andsens commented on docs/configuration/prometheus-frontend.md
> +  # The query endpoint URL of Prometheus-API compatible service to which the query-frontend should connect to.
> of Prometheus-API

"of *a* Prometheus-API"

2021-11-25 20:47 UTC, andsens commented on docs/configuration/prometheus-frontend.yml
> +  # The query endpoint URL of Prometheus-API compatible service to which the query-frontend should connect to.
> of Prometheus-API

"of *a* Prometheus-API"

2021-11-26 02:23 UTC, srijan55 commented
> Awesome. This explains very succinctly what the parameter is for.

Thanks. I made an unsigned commit and to resolve it did something wrong ... will clean it up or may be abandon this and create a new one.

2021-11-29 05:46 UTC, srijan55 commented
@andsens  have a look again when you have a moment. Also suggest someone who can be second reviewer and also help with the merge if everything is fine

2022-01-21 05:38 UTC, alvinlin123 commented on CHANGELOG.md
> +* [BUGFIX] Updated documentation with more details about `-frontend.downstream_url`. #3039
I don't think we typically up a CHANGELOG item for doc update (@bboreham correct me if I'm wrong). But if we do, I would say this change is more of an `ENHANCEMENT` than `BUGFIX` :-)

2022-01-21 05:39 UTC, alvinlin123 approved these changes

2022-03-30 18:07 UTC, friedrich-at-adobe commented on CHANGELOG.md
> +* [BUGFIX] Updated documentation with more details about `-frontend.downstream_url`. #3039
```suggestion
```

2022-04-21 19:38 UTC, merged