fix: set MemberlistKV on distributor ha_tracker kvstore
cortexproject/cortex pull request #4811
Opened 2022-08-03 15:41 UTC by sywesk

Signed-off-by: Benjamin Bourgeais <wixdesq@gmail.com>

**What this PR does**: 

When choosing the memberlist kv store for  the HA Tracker feature on the distributor, cortex crashes. Upon closer inspection, it seems that the MemberlisKV function was nil. I added the missing initialization for it to work.

**Which issue(s) this PR fixes**: None, I directly fixed the bug (one liner).

**Checklist**
- [ ] Tests updated
- [ ] Documentation added (no new feature, just a fix for an existing behavior)
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-08-04 19:45 UTC, friedrichg reviewed
I tested your change and I don't see the panic anymore
https://gist.github.com/friedrichg/820cf9420da1d43f257f98b366057e85

But I do see a different problem:
```
codec not registered in KV: replicaDesc
```

2022-08-05 10:10 UTC, sywesk commented
@friedrichg Thanks a lot for your feedback ! 

I initially thought it was only a forgotten MemberlistKV func, but I was wrong. It seemed like the ring codec wasn't enough because it only exposed the `ringDesc` codec and not the `replicaDesc` one. So I added the `distributor.GetReplicaDescCodec()` to the list of registered codecs for the memberlistKV.

However, i'd really appreciate some feedback on the codec registration, because I don't have the necessary hindsight on cortex's codebase and I feel like that it might not be the way to go.

2022-08-05 16:58 UTC, friedrichg requested changes
Still not good. All HA samples are rejected with
```
level=error ts=2022-08-05T16:55:11.428905229Z caller=ha_tracker.go:397 msg="rejecting sample" err="failed to CAS-update key ha-tracker/fake/one: invalid type: *distributor.ReplicaDesc, expected Mergeable"
```
it works fine with kvstore: consul

2022-08-08 18:59 UTC, danielblando commented
Hi @sywesk 

 I have spent some time recently taking a look at memberlist. I dont think memberlist was created to work with ha_tracker. Probably the main reason is the propagation delay. As it s gossip protocol, we don't have a consensus on distributor fast. 

 About the issue of ReplicaDesc be supported as a coded to the Memberlist. The work that i can imagine you will have is more on the [Mergeable](https://github.com/cortexproject/cortex/blob/master/pkg/ring/kv/memberlist/mergeable.go) interface. All codecs supported by memberlist need to implement the interface. Ex: implementation for the ringDesc (https://github.com/cortexproject/cortex/blob/master/pkg/ring/model.go#L185)

2022-08-09 07:09 UTC, sywesk commented
@danielblando Thanks a lot ! Indeed, that's what I was fearing. It seemed to me that it was too big of a rabbithole to have been left here unwillingly. I think you're right about the gossip protocol not being fast enough for the distributor, so I'll drop my merge request as I don't want to produce code that doesn't make sense for the project.

2022-08-09 07:09 UTC, closed without merging