[Vote] Governance update around maintainership
cortexproject/cortex pull request #4875
Opened 2022-09-21 00:51 UTC by alvinlin123

I would like to call an official vote to update the governance with changes around maintainership. Please see  the diff in this PR for the changes. 

Per [existing governance rule](https://cortexmetrics.io/docs/contributing/governance/#changes-in-governance), 2/3 majority votes are required for the changes to pass. 

Please cast your yes/no vote as comment in this PR, I will leave the vote open for 14 days (including weekends) or until all maintainer voted; whichever comes first.

2022-09-21 16:35 UTC, alvinlin123 commented
+1 binding.

2022-09-21 16:43 UTC, alanprot approved these changes

2022-09-21 16:44 UTC, alanprot commented
+1 binding.

2022-09-22 17:44 UTC, friedrichg requested changes
Just some spelling corrections, otherwise good :+1:

2022-09-22 17:44 UTC, friedrichg commented on GOVERNANCE.md
> +Maintainers should indicate their yes/no vote on that issue or PR, and after a suitable period of time (minimum 2 business weeks), the votes will be tallied and the outcome noted. Mainainers who do n
```suggestion
Maintainers should indicate their yes/no vote on that issue or PR, and after a suitable period of time (minimum 2 business weeks), the votes will be tallied and the outcome noted. Maintainers who do not cast a vote, after a suitable period of time, are not included in the majority calculation.
```

2022-09-22 17:56 UTC, friedrichg approved these changes

2022-09-29 17:05 UTC, jtlisi approved these changes
+1 binding

2022-10-05 22:20 UTC, alvinlin123 commented
With 4/4 +1s, I declare the governance update is effective as of now :)

2022-10-05 22:20 UTC, merged