update getting started doc
cortexproject/cortex pull request #4880
Opened 2022-09-26 16:30 UTC by songjiayang

1. change single-process-config-blocks.yaml to single-process-config-blocks-local.yaml
2. add specific tag for cortex docker image

Signed-off-by: songjiayang <songjiayang1@gmail.com>

2022-09-26 16:34 UTC, alanprot commented
Humm.. i think changing to local make sense.

But I'm not sure about if we should pin a version as we will need to remember on all release to update this.

2022-09-26 16:52 UTC, yeya24 commented
> But I'm not sure about if we should pin a version as we will need to remember on all release to update this.

Yeah for getting started, using the latest image is better.

2022-09-27 13:49 UTC, songjiayang commented
using latest version for default is better, but now when pull image with `latest` tag , it will raise a error:

```
docker run -d --name=cortex2 --network=cortex \
>     -v $(pwd)/docs/configuration/single-process-config-blocks-local.yaml:/etc/single-process-config-blocks-local.yaml \
>     -p 9002:9009 \
>     quay.io/cortexproject/cortex \
>     -config.file=/etc/single-process-config-blocks-local.yaml \
>     -ring.store=consul \
>     -consul.hostname=consul:8500 \
>     -distributor.replication-factor=3
Unable to find image 'quay.io/cortexproject/cortex:latest' locally
docker: Error response from daemon: manifest for quay.io/cortexproject/cortex:latest not found: manifest unknown: manifest unknown.
```

2022-09-28 16:24 UTC, yeya24 commented
Umm, yeah I don't see we have a image tagged with `latest` on quay... 
So probably the doc doesn't work from the beginning.

2022-09-28 17:28 UTC, friedrichg commented
> Next we're going to show how you can run a scale out Cortex cluster using Docker. We'll need:
> - A built Cortex image.

This is why the example worked for whoever wrote it. It's go developer focused. If you run `make`, you get a cortex image.
But I agree is not clear and you should definitely specify a version. (v1.13.0 is fine)

The other thing that I would love to remove from this "getting started" is the notion of consul, I think we can just use memberlist. But we can leave that for another PR

2022-09-28 17:37 UTC, friedrichg commented on docs/getting-started/_index.md
> +    quay.io/cortexproject/cortex  \
```suggestion
    quay.io/cortexproject/cortex \
```

2022-09-29 13:26 UTC, friedrichg approved these changes

2022-10-07 14:49 UTC, friedrich-at-adobe requested changes

2022-10-07 14:49 UTC, friedrich-at-adobe commented on docs/getting-started/_index.md
>  Unless reconfigured this starts a single Cortex node storing blocks to S3 in bucket `cortex`.
This comment no longer makes sense. Needs update

2022-10-07 14:49 UTC, friedrichg requested changes

2022-10-07 14:49 UTC, friedrichg commented on docs/getting-started/_index.md
>  Unless reconfigured this starts a single Cortex node storing blocks to S3 in bucket `cortex`.
this comment no longer makes sense. Needs update

2022-10-17 12:00 UTC, friedrichg approved these changes

2022-11-03 16:41 UTC, alvinlin123 commented
> Umm, yeah I don't see we have a image tagged with `latest` on quay... So probably the doc doesn't work from the beginning.

We should fix this: https://github.com/cortexproject/cortex/issues/4951

2022-11-03 16:42 UTC, alvinlin123 approved these changes

2022-11-03 16:43 UTC, merged