Parallelize RING package tests
cortexproject/cortex pull request #5151
Opened 2023-02-15 23:11 UTC by moki1202

Signed-off-by: Shashank Singh [shashanksingh819@gmail.com](mailto:shashanksingh819@gmail.com)

**What this PR does**:
Optimizes go tests in `ring` package 

**Which issue(s) this PR fixes**:
Partially Fixes #3922 

Previous:
```
go test ./pkg/ring/ -v -count 1 -parallel 1
ok  	github.com/cortexproject/cortex/pkg/ring 71.475s
```
after:
```
go test ./pkg/ring/ -v -count 1
ok  	github.com/cortexproject/cortex/pkg/ring	10.188s

```
**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2023-02-15 23:15 UTC, moki1202 commented
@friedrichg tried my best, please let me know if this PR needs improvement. Wanted to ask a question, is it possible that using t.parallel() in some places might actually increase the already low test times rather than optimizing it further?

2023-02-16 04:05 UTC, friedrichg commented
Thanks for your contribution.

@moki1202 As a general rule, it will use more cpus and will be faster. The only risk is we can make tests flaky if there is hidden bad concurrency in cortex.

Always sign your commits so it can pass the DCO. See [details](https://github.com/cortexproject/cortex/pull/5151/checks?check_run_id=11374077795)

2023-02-16 15:09 UTC, friedrichg commented
Please look at the lint errors and fix them

2023-02-20 13:41 UTC, moki1202 commented
**On my machine**-
after-
```
go test -tags netgo -timeout 30m -race -count 1 ./pkg/ring/...
ok      github.com/cortexproject/cortex/pkg/ring        31.153s
```

2023-02-20 20:58 UTC, friedrichg requested changes
Awesome job! 

You are almost there, there is a few missing.

Following files still need some t.Parallel after t.Run

pkg/ring/kv/dynamodb/dynamodb_test.go
pkg/ring/kv/memberlist/memberlist_client_test.go
pkg/ring/model_test.go
pkg/ring/replication_set_tracker_test.go
pkg/ring/replication_strategy_test.go
pkg/ring/ring_test.go

2023-02-21 16:35 UTC, moki1202 commented
> Awesome job!
> 
> You are almost there, there is a few missing.
> 
> Following files still need some t.Parallel after t.Run
> 
> pkg/ring/kv/dynamodb/dynamodb_test.go pkg/ring/kv/memberlist/memberlist_client_test.go pkg/ring/model_test.go pkg/ring/replication_set_tracker_test.go pkg/ring/replication_strategy_test.go pkg/ring/ring_test.go

Done! Added t.parallel() to t.run() functions that I missed. Also added comment where parallelization wouldn't have worked.

2023-02-24 16:33 UTC, friedrichg approved these changes
Thanks for your patience. 

I noticed you skipped pkg/ring/kv/dynamodb/client_test.go too, but just add comments there, I don't think we can parallelize there too much.

Approved with minor nits.

2023-02-24 16:38 UTC, moki1202 commented
> Thanks for your patience.
> 
> I noticed you skipped pkg/ring/kv/dynamodb/client_test.go too, but just add comments there, I don't think we can parallelize there too much.
> 
> Approved with minor nits.

@friedrichg This is wierd, thought I'd covered every file. Will look into this again!

2023-02-28 13:05 UTC, moki1202 commented on pkg/ring/model_test.go
> +	//parallel testing causes data race
@friedrichg Will check this again. Now I understand why you emphasized on creating smaller PRs 😅. Much easier to work with, that way.

2023-08-12 09:37 UTC, closed without merging