add/support enabled_tenants and disabled_tenants feature in storegateway
cortexproject/cortex pull request #5186
Opened 2023-02-28 16:21 UTC by moki1202

Signed-off-by: Shashank [shashanksingh819@gmail.com](mailto:shashanksingh819@gmail.com)

What this PR does: Now adds/supports `enabled_tenants` and` disabled_tenants` in package `storegateway`

Fixes #5133

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2023-03-02 12:21 UTC, moki1202 commented
@friedrich-at-adobe Do I need to create a new function to filter out users that are not allowed?

2023-03-02 12:40 UTC, friedrichg commented
@moki1202 Store-gateways download the bucket index for the tenant and all the blocks. I would expect that this PR to ignore users discovered in S3 that are not allowed. a new function is not required, use `allowedTenants.IsAllowed`
See this [PR](https://github.com/cortexproject/cortex/pull/5116) for an example

2023-03-03 09:18 UTC, friedrichg commented
@moki1202 filterUsers function is already in the right places
https://github.com/cortexproject/cortex/blob/47733ddab802acef66f6ab7be41ebb24a512a7ce/pkg/storegateway/bucket_index_metadata_fetcher.go#L61

https://github.com/cortexproject/cortex/blob/47733ddab802acef66f6ab7be41ebb24a512a7ce/pkg/storegateway/bucket_stores.go#L212

Concentrate making changes on https://github.com/cortexproject/cortex/blob/master/pkg/storegateway/sharding_strategy.go
to implement this feature on both normal sharding and shuffle sharding
and don't forget to update/include tests in sharding_strategy_test.go

2023-05-22 14:05 UTC, moki1202 commented
@friedrichg Apologies for the late follow up. I've written a test for the changes. Can you please confirm whether its the correct way or not? Once I get the confirmation I'll try completing this ASAP.

2023-06-03 11:29 UTC, moki1202 commented
@friedrichg I've tried a lot but I am struggling while updating the tests. Can you please help me out here? I would just ask for your help in updating the defaultShardingStrategy tests. I'll try doing the other ones after.

2023-07-25 11:10 UTC, moki1202 commented
@friedrichg I've tried a lot but I am struggling while updating the tests. Can you please help me out here? I would just ask for your help in updating the defaultShardingStrategy tests. I'll try doing the other ones after.

2023-11-07 03:31 UTC, friedrichg requested changes

2023-11-07 03:33 UTC, friedrichg commented on pkg/storegateway/sharding_strategy_test.go
> +		"two ACTIVE instances in the ring with replication factor = 1 and one tenant disabled": {
Unfortunately, this function does not test FilterUsers, it tests FilterBlocks. So this is not the right place

2023-11-10 12:15 UTC, friedrichg commented
Thanks, partially included in https://github.com/cortexproject/cortex/pull/5638

2023-11-10 12:15 UTC, closed without merging