fix: unit test anomalous error, defer not release port correctly
cortexproject/cortex pull request #5231
Opened 2023-03-27 06:55 UTC by yiyang5055

**What this PR does**:
unit test anomalous error,  port already in used. defer not release port correctly.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2023-03-27 17:38 UTC, alanprot commented
Hi, Thanks for this.

Can you paste the error that you are trying to fix?

2023-03-29 07:11 UTC, yiyang5055 commented
> Hi, Thanks for this.
> 
> Can you paste the error that you are trying to fix?

sorry，i forgot to save.
In the unit test case of TestJoinMembersWithRetryBackoff, using getFreePorts to get the available ports, I encountered an error that a port is in use. I suspect that the port release in getFreePorts is a bit slow。
so through this PR I am trying to fix。

2023-03-29 18:13 UTC, alanprot approved these changes

2023-03-31 14:28 UTC, friedrichg requested changes
I can see why this PR releases the port correctly.
But it adds different problem, the function can now return repeated ports which will clash.
See https://github.com/cortexproject/cortex/issues/5038

2023-05-09 11:20 UTC, closed without merging