Add unit test for resolveConflicts function
cortexproject/cortex pull request #5233
Opened 2023-03-27 11:02 UTC by dogukanteber

**What this PR does**:
This PR adds unit test to `resolveConflicts` function

**Which issue(s) this PR fixes**:
Fixes #5079 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2023-03-29 16:16 UTC, friedrichg requested changes

2023-03-29 16:16 UTC, friedrichg commented on pkg/ring/model_test.go
> +				"ing2": {State: LEFT, Tokens: []uint32{}},
```suggestion
				"ing2": {State: LEFT, Tokens: nil},
```

2023-03-29 16:16 UTC, friedrichg commented on pkg/ring/model_test.go
> +				"ing1": {State: LEAVING, Tokens: []uint32{}},
```suggestion
				"ing1": {State: LEAVING, Tokens: nil},
```

2023-03-29 16:16 UTC, friedrichg commented on pkg/ring/model_test.go
> +				}
```suggestion
				assert.Equal(t, actualInstance, tt.want[key])
```

2023-03-29 16:16 UTC, friedrichg commented on pkg/ring/model_test.go
> +					if len(actualInstance.Tokens) == len(expectedInstance.Tokens) && len(actualInstance.Tokens) != 0 {
DeepEqual was telling you the right thing.
`nil` is different from empty array `[]uint32{}`

assertEqual tells you this more clearly. testify is a great library

2023-03-31 14:12 UTC, friedrichg approved these changes

2023-03-31 20:35 UTC, alvinlin123 approved these changes

2023-03-31 20:35 UTC, merged