Add user label to ruler query and write metrics
cortexproject/cortex pull request #5312
Opened 2023-05-01 18:32 UTC by rajagopalanand

**What this PR does**:

Adding user label to cortex_ruler_queries_failed_total, cortex_ruler_queries_total, cortex_ruler_write_requests_failed_total, cortex_ruler_write_requests_total metrics. This would allow for better tracking of failures at a user level

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2023-05-01 20:29 UTC, alvinlin123 reviewed
overall looks good, but I think some test should be updated/added for the `user` label.

2023-05-01 21:28 UTC, yeya24 commented
The change looks okay to me. Please make sure we mention the metrics we are going to change in the release note.
And those metrics are counters so I feel the cardinality change for these metrics is okay.

2023-05-02 10:52 UTC, friedrichg reviewed
Looks good, like Alvin says: just add 1 test using testutil.GatherAndCompare

2023-05-04 01:30 UTC, alvinlin123 requested changes
Nice enhancement, but I think something is wrong with the PR; it includes changes that are already in the `cortexporject:master` branch. Can you fix this before I merge this PR?

2023-05-04 01:30 UTC, alvinlin123 commented on .github/workflows/test-build-deploy.yml
> +            docker pull quay.io/cortexproject/cortex:v1.15.1
this looks like a change that is already in `cortexproject:master`

2023-05-04 01:30 UTC, alvinlin123 commented on .gitignore
> +cmd/test-exporter/test-exporter-*
this looks like a change that is already in cortexproject:master

2023-05-04 20:53 UTC, alvinlin123 approved these changes

2023-05-04 21:24 UTC, yeya24 approved these changes
Thanks

2023-05-04 21:24 UTC, merged