Add ingester flag to add admin contact details in limiter error messages
cortexproject/cortex pull request #5460
Opened 2023-07-15 11:39 UTC by kumanik

**What this PR does**:
Adds an admin contact address flag to the ingester and uses it while printing error messages when hitting limits.

**Which issue(s) this PR fixes**:
Fixes #5452 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2023-07-15 11:50 UTC, kumanik commented
@friedrichg Have a look 

I was thinking of adding tests for checking contact details at-
https://github.com/kumanik/cortex/blob/81a3cd3c5b5bedb9c7c8208ea7a059fbaf1c7730/pkg/ingester/limiter_test.go#L504C2-L507

Or should I create a completely new test?

2023-07-15 15:56 UTC, friedrichg requested changes
Thank you for your contribution!

You don't need to add any additional tests, just keep the current tests working.

2023-07-15 15:56 UTC, friedrichg commented on pkg/ingester/ingester.go
> +	AdminContactDetails string `yaml:"admin_contact"`
```suggestion
	AdminLimitMessage string `yaml:"admin_limit_message"`
```

2023-07-15 15:56 UTC, friedrichg commented on pkg/ingester/ingester.go
> +	f.StringVar(&cfg.AdminContactDetails, "ingester.admin-contact", "", "Add site administrator contact details for customising error messages")
```suggestion
	f.StringVar(&cfg.AdminLimitMessage, "ingester.admin-limit-message", defaultAdminLimitMessage, "Customize the message contained in limit errors")
```
Where defaultAdminLimitMessage is a string var with "please contact administrator to raise it" that can be used in tests

2023-07-15 15:56 UTC, friedrichg commented on pkg/ingester/limiter.go
> +	}
```suggestion
```
This is not needed

2023-07-15 15:56 UTC, friedrichg commented on pkg/ingester/limiter.go
> +		minNonZero(localLimit, globalLimit), adminContact, localLimit, globalLimit, actualLimit)
```suggestion
	return fmt.Errorf("per-user series limit of %d exceeded, %s (local limit: %d global limit: %d actual local limit: %d)",
		minNonZero(localLimit, globalLimit), adminLimitMessage, localLimit, globalLimit, actualLimit)
```

2023-07-16 16:43 UTC, friedrichg commented on docs/configuration/config-file-reference.md
> +# CLI flag: -ingester.admin-contact
needs to change

2023-07-17 17:23 UTC, friedrichg reviewed
Good job @kumanik , the only thing missing is a FEATURE in the CHANGELOG.

2023-07-18 13:21 UTC, friedrich-at-adobe commented on CHANGELOG.md
> +* [FEATURE] Ingester: added `-admin-limit-message` to customize the message contained in limit errors.#5452
```suggestion
* [FEATURE] Ingester: added `-admin-limit-message` to customize the message contained in limit errors.#5460
```

2023-07-18 14:02 UTC, kumanik commented
It is done I suppose

2023-07-18 14:45 UTC, friedrichg approved these changes
Thank you!

2023-07-18 14:46 UTC, merged

2023-07-18 15:00 UTC, kumanik commented
No, thank you. Really glad I could contribute.