Query Frontend: queries with negative offset should check whether it is cacheable or not
cortexproject/cortex pull request #5719
Opened 2023-12-26 16:46 UTC by pawarpranav83

**What this PR does**:

Checks whether offset is negative or not, and if negative, it does not cache the query result.

**Which issue(s) this PR fixes**:
Fixes #5678 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2023-12-26 16:48 UTC, pawarpranav83 commented
@yeya24

2023-12-27 07:17 UTC, yeya24 commented
@pawarpranav83 Thanks. Same comment as https://github.com/thanos-io/thanos/pull/7011

2023-12-28 07:31 UTC, yeya24 approved these changes
Thanks

2023-12-28 07:35 UTC, yeya24 requested changes

2023-12-28 07:35 UTC, yeya24 commented on CHANGELOG.md
> +* [BUGFIX] Query Frontend: queries with negative offset should check whether it is cacheable or not. #5719
Let's move this entry to the end to the end. It should be grouped together with `BUGFIX` items

2023-12-28 13:48 UTC, yeya24 approved these changes

2023-12-28 13:48 UTC, merged