Stepping down as Cortex maintainer
cortexproject/cortex pull request #6082
Opened 2024-07-11 18:51 UTC by alvinlin123

I can't believe this day would come, but I am stepping down as Cortex maintainer because I no longer have capacity to give Cortex the love it needs anymore. Also, Cortex is in good hands with existing maintainers from diverse set of companies.

It's been a fun ride. I still remember my [first Cortex PR](https://github.com/cortexproject/cortex/pull/2741) that allows me to build Cortex in my employer's network, and [the day I became maintainer 3 years ago](https://github.com/cortexproject/cortex/commit/b4daa22055ffec14311d8b5d2d9429f1bd575dad). It was full of joys and emotions. But there is always an end to a party, and for me it's today. 

Thank you all for the great work and support thus far!

2024-07-11 18:55 UTC, alanprot commented
:(

Thanks for all the good work @alvinlin123 

Sad to see you go! =/

2024-07-11 19:24 UTC, CharlieTLe approved these changes
Thanks for all of your contributions, and best of luck to your future endeavors!

2024-07-12 06:13 UTC, alolita commented
@alvinlin123 thank you for your technical leadership and work on the project. Hope to still see you on the project and in the open source observability space!

2024-07-12 07:43 UTC, friedrichg commented
More than anything, you've trained me well in kindness and leadership by example. 
Like you said, cortex is in great shape right now and that is because of all the work you did
🙇

2024-07-12 07:47 UTC, friedrichg requested changes
@alvinlin123 Please put yourself among the greatest. You've earned it https://github.com/cortexproject/cortex/blob/master/README.md#emeritus-maintainers

2024-07-30 07:20 UTC, friedrichg approved these changes

2024-07-30 07:21 UTC, merged